---
- hosts: cache-server
  become: yes
  tasks:
    - name: Install redis server
      ansible.builtin.apt:
        name:
          - redis-server
    - name: Install git
      ansible.builtin.apt:
        name:
          - git
    - name: Install rsync package
      ansible.builtin.apt:
        name:
          - rsync
    
    - name: Install lsof package 
      ansible.builtin.apt:
        name:
          - lsof

    - name: Install python3 pip
      ansible.builtin.apt:
        name:
          - python3-pip

    - name: Install python3 virtual env
      ansible.builtin.apt:
        name:
          - python3-virtualenv

    - name: Add openresty GPG key
      ansible.builtin.apt_key:
        url: https://openresty.org/package/pubkey.gpg
    - name: Add openresty repository
      ansible.builtin.apt_repository:
        repo: deb http://openresty.org/package/debian bullseye openresty
    - name: Install openresty
      ansible.builtin.apt:
        name:
          - openresty
          
      