---
- hosts: cache-server
  become: True
  tasks: 
    - name: Create the virtual environment 
      ansible.builtin.pip:
        requirements: /opt/cache_server/requirements.txt
        virtualenv: /opt/cache_server/venv
        virtualenv_python: python3.9

    - name: Copy log_export supervisor config file from local to remote.
      ansible.builtin.copy:
        src: /opt/cache_server/cdn_exporter.conf
        dest: /etc/supervisor/conf.d/cdn_exporter.conf
        remote_src: true
    
    - name: Reload supervisor config
      ansible.builtin.command:
        cmd: supervisorctl reread

    - name: Run python log exporter using supervisor
      ansible.builtin.command:
        cmd: supervisorctl start all
    
    - name: Reload supervisorctl
      ansible.builtin.command:
        cmd: supervisorctl reload