---
- hosts: cache-server
  name: Synchronize code
  become: yes
  tasks:
  - name: Clone git
    ansible.builtin.git:
      repo: https://NguyenQuangMinh0504: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@github.com/NguyenQuangMinh0504/cdn_server.git
      dest: /opt/cache_server
      update: yes
      clone: yes
      force: yes