---
- hosts: cache-server-2
  name: Synchronize code
  become: yes
  tasks:
  - name: Synchronize config
    ansible.posix.synchronize:
      src: /Users/nguyenquangminh/Desktop/PROJECT/solo-projects/cdn_server/
      dest: /home/nguyenquangminh/cdn_server/
