---
- hosts: cache-server
  name: Running process
  become: yes
  tasks:
    - name: Stop Openresty service
      ansible.builtin.service:
        name: openresty
        state: stopped
      
    - name: Run openresty cache server
      ansible.builtin.command:
        chdir: /opt/cache_server
        cmd: openresty -c cache_server.conf -p /opt/cache_server
