---
- hosts: cache-server
  name: Running process
  become: yes
  tasks:
    - name: Find all process using port 80
      ansible.builtin.shell: "lsof -t -i:80"
      register: processes_on_port

    - name: Stop all processes running on port 80
      ansible.builtin.shell: "kill -9 {{ item }}"
      with_items: "{{ processes_on_port.stdout_lines }}"
      ignore_errors: yes
      
    - name: Run openresty cache server
      ansible.builtin.command:
        chdir: /opt/cache_server
        cmd: openresty -c cache_server.conf -p /opt/cache_server
