---
- hosts: cache-server
  name: Synchronize code
  become: yes
  tasks:
  - name: Clone git
    ansible.builtin.git:
      repo: https://github.com/NguyenQuangMinh0504/cdn_server
      dest: /opt/cache_server
      update: yes
      clone: yes
      force: yes